dino = [
    ['bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','bg','bg','bg','ot','ot','ot','bg','bg','bg','bg','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','bg','ot','ot','bc','bc','bc','ot','ot','bg','bg','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','ot','bc','bc','ec','ew','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','ot','bc','bc','bc','ec','ec','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','ot','ot','ot','ot','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg'],
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
    ['bg','bg','bg','bg','bg','bg','bg','bg','ot','bc','bc','bc','bc','bc','bc','ot','bg','bg','bg','bg']
]
